# Generated by Django 5.1.2 on 2024-10-09 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('frequency', models.IntegerField(help_text='Frequency in minutes to check the website')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_details', models.JSONField()),
                ('response_details', models.JSONField()),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='TestConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('status_code', 'Status Code'), ('keyword', 'Keyword in Body'), ('response_time', 'Response Time')], max_length=100)),
                ('expected_value', models.CharField(help_text='Expected value for this test', max_length=100)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='monitor.action')),
            ],
        ),
    ]
