# Generated by Django 5.1.2 on 2024-10-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_testresults_delete_testconfiguration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestResults',
            new_name='TestResult',
        ),
    ]
