# Generated by Django 5.1.2 on 2024-10-10 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_rename_testresults_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='sensor',
        ),
        migrations.AddField(
            model_name='testresult',
            name='actual_value',
            field=models.CharField(blank=True, help_text='Actual value observed during the test', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SensorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.action')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='actions',
            field=models.ManyToManyField(related_name='sensors', through='monitor.SensorAction', to='monitor.action'),
        ),
    ]
