# Generated by Django 5.1.2 on 2024-10-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_action_sensor_testresult_actual_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='actions',
        ),
        migrations.AddField(
            model_name='action',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='monitor.sensor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SensorAction',
        ),
    ]
