# Generated by Django 5.1.2 on 2024-10-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_remove_sensor_actions_action_sensor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='response_details',
        ),
        migrations.RemoveField(
            model_name='action',
            name='test_results',
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE')], default='GET', max_length=10),
        ),
    ]
