# Generated by Django 5.1.2 on 2024-10-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_remove_action_response_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='assertion_type',
            field=models.CharField(choices=[('status_code', 'Status Code'), ('contains_keyword', 'Contains Keyword'), ('element_exists', 'Element Exists'), ('json_key_exists', 'JSON Key Exists')], default='status_code', max_length=50),
        ),
        migrations.AddField(
            model_name='action',
            name='expected_value',
            field=models.CharField(default=1, help_text='The expected value for this assertion', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='selector',
            field=models.CharField(blank=True, help_text='CSS Selector (for element_exists type)', max_length=200, null=True),
        ),
    ]
