# Generated by Django 5.1.2 on 2024-10-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_action_assertion_type_action_expected_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_path',
            field=models.CharField(default=''),
        ),
    ]
