# Generated by Django 5.1.2 on 2024-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_action_action_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='request_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
