# Generated by Django 5.1.2 on 2024-10-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_action_request_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='request_details',
            new_name='request_body',
        ),
    ]
