# Generated by Django 5.1.2 on 2024-10-12 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_rename_request_details_action_request_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='timestamp',
            new_name='last_execution',
        ),
    ]
