# Generated by Django 5.1.2 on 2024-10-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_rename_timestamp_action_last_execution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='request_body',
            new_name='payload',
        ),
    ]
