# Generated by Django 5.1.2 on 2024-10-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_remove_action_selector_action_selenium_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='sequence',
            field=models.IntegerField(default=0, help_text='Order of the command'),
        ),
    ]
