# Generated by Django 5.1.2 on 2024-10-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_action_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='selenium_script',
            field=models.CharField(blank=True, help_text='Selenium Style script)', null=True),
        ),
    ]
