# Generated by Django 5.1.2 on 2024-10-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_testresult_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='body',
            field=models.CharField(blank=True, help_text='Add more context to the results', max_length=255, null=True),
        ),
    ]
