# Generated by Django 5.1.2 on 2024-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='selenium_script',
            field=models.TextField(blank=True, help_text='Selenium Style script', null=True),
        ),
    ]
