# Generated by Django 5.1.2 on 2024-10-15 14:04

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_alter_action_selenium_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='selenium_script',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Selenium Style script', null=True)),
        ),
    ]
