# Generated by Django 5.1.2 on 2024-10-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0026_userprofile_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_contains_keyword',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_screenshot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_selenium',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_status_code',
            field=models.BooleanField(default=True),
        ),
    ]
