# Generated by Django 5.1.2 on 2024-10-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_userprofile_notify_contains_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_bot_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_ids',
            field=models.JSONField(default=list),
        ),
    ]
